/*SELECT FIRST_MATCH_Javier.*, TOWARDS_THIRD_MATCH.Etapa_Dirección
FROM FIRST_MATCH_Javier
LEFT JOIN TOWARDS_THIRD_MATCH
ON FIRST_MATCH_Javier.ID_NumRevista = TOWARDS_THIRD_MATCH.ID_NumRevista */

CREATE TABLE THIRD_MATCH_Javier AS
SELECT FIRST_MATCH_Javier.*, TOWARDS_THIRD_MATCH.Etapa_Dirección
FROM FIRST_MATCH_Javier
LEFT JOIN TOWARDS_THIRD_MATCH
ON FIRST_MATCH_Javier.ID_NumRevista = TOWARDS_THIRD_MATCH.ID_NumRevista

