/*SELECT * FROM THIRD_MATCH_Javier
CREATE TABLE TITLES_METADATA_TABLE_Javier AS
SELECT ID_Title, Etapa_Dirección, Type_title, género FROM THIRD_MATCH_Javier; */
SELECT * FROM TITLES_METADATA_TABLE_Javier

